/*
 *   IRC - Internet Relay Chat, src/version.c
 *   Copyright (C) 1990 Chelsea Ashley Dyerman
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 1, or (at your option)
 *   any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program; if not, write to the Free Software
 *   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

/*
 * This file is generated by version.c.SH. Any changes made will go away.
 */

#include "patchlevel.h"
#include "serno.h"

const char *generation = "1";
const char *creation = "Thu Feb 6 2014 at 05:46:49 AST";
const char *platform = "FreeBSD fbsd 9.1-RC2 FreeBSD 9.1-RC2 #0: Thu Oct 18 14:51:22 EDT 2012     root@fbsd91rc2.vm:/usr/obj/usr/src/sys/XENHVM  amd64";
const char *ircd_version = PATCHLEVEL;
const char *serno = SERNO;

const char *infotext[] =
{
  "IRC --",
  "Based on the original code written by Jarkko Oikarinen",
  "Copyright 1988, 1989, 1990, 1991 University of Oulu, Computing Center",
  "Copyright (c) 1996-2001 Hybrid Development Team", 
  "Copyright (c) 2002-2009 ircd-ratbox Development Team",
  "Copyright (c) 2005-2010 charybdis development team",
  "",
  "This program is free software; you can redistribute it and/or",
  "modify it under the terms of the GNU General Public License as",
  "published by the Free Software Foundation; either version 2, or",
  "(at your option) any later version.",
  "",
  " ",
  "elemental-ircd is a fork of the ShadowIRCD project created to meet",
  "PonyChat's needs and keep the now-defunct ShadowIRCD project's goals",
  "alive.",
  " ",
  "The elemental-ircd team is listed in nick-alphabetical order:",
  " ",
  "aji, Alex Iadicico <alex -at- ajitek.net>",
  "lyska, Sam Dodrill <shadowh511 -at- gmail.com>>",
  "Kabaka, Kyle Johnson <kabaka -at- ponychat.net>",
  " ",
  "ShadowIRCd 6 is a modern restart of the old ShadowIRCd project",
  "based on Charybdis with a few additional features to make it appeal ",
  "more to more users. We try to work as closely as possible with the ",
  "Charybdis team.",
  " ",
  "The ShadowIRCd team is listed in nick-alphabetical order:",
  " ",
  "jdhore, JD Horelick <jdhore1 -at- gmail.com>",
  "Taros, Brett Greenham <taros34 -at- hotmail.com>",
  " ",
  "Some ShadowIRCd 6 features such as the oper-override and remote",
  "RESTART, DIE and MOD* commands were borrowed from ircd-seven.",
  " ",
  "ircd-seven is written by:",
  " ",
  "spb, Stephen Bennett <spb -at- attenuate.org>",
  " ",
  "Charybdis started as an evolution from ircd-ratbox. Its development",
  "is led by a team of dedicated developers who have put a lot of time",
  "into the project, and it has seen use on a variety of different",
  "network configurations.",
  " ",
  "The charybdis core team is listed in nick-alphabetical order:",
  " ",
  "jilles, Jilles Tjoelker <jilles -at- stack.nl>",
  "nenolod, William Pitcock <nenolod -at- nenolod.net>",
  "spb, Stephen Bennett <spb -at- attenuate.org>",
  " ",
  "The following people have made contributions to the Charybdis releases,",
  "in nick-alphabetical order:",
  " ",
  "AndroSyn, Aaron Sethman <androsyn -at- ratbox.org>",
  "anfl, Lee Hardy <lee -at- leeh.co.uk>",
  "beu, Elfyn McBratney <elfyn.mcbratney -at- gmail.com>",
  "dwr, Valery Yatsko <dwr -at- shadowircd.net> ",
  "Entrope, Michael Poole <mdpoole -at- trolius.org> ",
  "gxti, Michael Tharp <gxti -at- partiallystapled.com>",
  "jdhore, JD Horelick <jdhore1 -at- gmail.com>",
  "mr_flea, Keith Buck <mr_flea -at- esper.net>",
  "Taros, Brett Greenham <taros -at- shadowircd.net>",
  "ThaPrince, Jon Christopherson <jon -at- vile.com>",
  "twincest, River Tarnell <river -at- attenuate.org>",
  "w00t, Robin Burchell <surreal.w00t -at- gmail.com>",
  " ",
  "Visit the elemental-ircd repo at: http://www.github.com/ponychat/elemental-ircd",
  "Visit us on IRC at: irc.ponychat.net #rainbow-factory",
  "",
  0,
};
